package stepDefinitions;

import cucumber.api.java.en.*;
import static org.junit.jupiter.api.Assertions.*;
import static stepDefinitions.AudioSteps.transcription;

import ManejoDeAudios.EliminarAudioEnCelular;
import org.apache.commons.text.similarity.LevenshteinDistance;
import utils.EstadoPrueba;

public class ValidacionesDeTranscripciones {

    private static final String RUTA_ARCHIVO_CELULAR = "/sdcard/Recordings/Call/";
    private static final String udid = "R9WW70LL61V"; // tu UDID
    private static final double UMBRAL_COINCIDENCIA = 90.0; // Porcentaje mínimo aceptable

    /* IVR_00 */ @Then("^Validar la transcripción con el texto esperado del menu principal$")
    public void validarTranscripcionMenuPrincipal() {
        String textoEsperado = "ingresa a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho más quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_01 */ @Then("^Validar la transcripción Menu Inicio, Ingreso a WhatsApp$")
    public void validarTranscripcionOpcion1() {
        String textoEsperado = "ingresa a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho más quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3  tu consulta será atendida por medio de whatsapp";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_02 */ @Then("^Validar la transcripción Comprar Servicios Claro, Servicios Hogar$")
    public void validarTranscripcionComprarServiciosClaroServiciosHogar() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrá consultar tu plan pagar tu factura y mucho más quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3  estás en la línea de ventas claro si tu consulta sobre un servicio diferente por favor finalizar la llamada vuelve a marcar ingresa por la opción 3 del menú principal para servicios hogar marca 1 comprar un plan pospago móvil marca 2 comprar celulares televisores computadores marca 3 adquirir servicios fijos o móviles para que empresa y pasarte a claro con tu mismo número marca 4 marca 9 si deseas escuchar de nuevo la información  bienvenido a la línea de ventas de claro hogar recuerda y tu consulta sobre servicio al cliente y no para comprar servicios por favor finaliza esta llamada vuelve a marcar ingresa por la opción 3 del menú principal dime lo que deseas adquirir por ejemplo quiero comprar internet hogar";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_03 */ @Then("^Validar la transcripción Comprar Servicios Claro, Plan Postpago Movil$")
    public void validarTranscripcionComprarServiciosClaroPlanPostpagoMovil() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 estas en la linea de ventas clave si tu consulta sobre un servicio diferente por favor finaliza esta llamada vuelve a marcar ingresa por la opcion 3 del menu principal para servicios hogar marca 1 comprar un plan postpago movil marcados comprar celulares televisores computadores marca 3 adquirir servicios fijos o moviles para tu empresa y pasarte a claro con tu mismo numero marca 4 marca 9 si deseas escuchar de nuevo la informacion en un momento te estaremos transfiriendo con un asesor";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_04 */ @Then("^Validar la transcripción Menu Inicio, Comprar Servicios Claro, Compra De Equipos$")
    public void validarTranscripcionMenuInicioComprarServiciosClaroCompraDeEquipos() {
        String textoEsperado = "ingreso whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 estas en la linea de ventas claro si tu consulta sobre un servicio diferente por favor finaliza esta llamada vuelve a marcar ingresa por la opcion 3 del menu principal para servicios hogar marca 1 comprar un plan postpago movil marcados comprar celulares televisores computadores marca 3 adquirir servicios fijos o moviles para tu empresa y pasarte a claro con tu mismo numero marca 4 marca 9 si deseas escuchar de nuevo la informacion en un momento te estaremos transfiriendo con un asesor";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_05 */ @Then("^Validar la transcripción Menu Inicio, Comprar Servicios Claro, Adquirir Servicios Y Pasarte a Claro$")
    public void validarTranscripcionMenuInicioComprarServiciosClaroAdquirirServiciosYPasarteaClaro() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 estas en la linea de ventas claro si tu consulta sobre un servicio diferente por favor finaliza esta llamada vuelve a marcar ingresa por la opcion 3 del menu principal para servicios hogar marca 1 comprar un plan postpago movil marca 2 comprar celulares televisores computadores marca 3 adquirir servicios fijos o moviles para tu empresa y pasarte a claro con tu mismo numero marca 4 marca 9 si deseas escuchar de nuevo la informacion aqui podras adquirir servicios exclusivamente para tu negocio o empresa si tu requerimiento es diferente te invitamos a llamar nuevamente y escuches con atencion nuestro menu principal";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_06 */ @Then("^Validar la transcripción Valida Menu Para Consultar Lineas$")
    public void validarTranscripcionOpcion2y4() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho más quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3  estás en la línea de ventas claro si tu consulta sobre un servicio diferente por favor finaliza esta llamada vuelve a marcar ingresa por la opción 3 del menú principal para servicios hogar marca 1 comprar un plan pospago móvil marca 2 comprar celulares televisores computadores marca 3 adquirir servicios fijos o móviles para que empresa y pasarte a claro con tu mismo número marca 4 marca 9 si deseas escuchar de nuevo la información  aquí podrás adquirir servicios exclusivamente para tu negocio o empresa si tu requerimientos diferente te invitamos a llamar nuevamente y escuché con atención nuestro menú principal";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_08 */ @Then("^Validar la transcripción Menu Principal, Asterisco, Consultar Saldo$")
    public void validarTranscripcionOpcion3y24() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por consulta paquetes activos si ese es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 quieres consultar el saldo de tu linea prepago marca 1 quieres comprar paquetes marca 2 quieres recargar tu linea prepago marca 3 quieres consultar tus productos financiados marca 4 quieres revisar tus paquetes activos marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 su linea tiene un saldo de 100 60 9 10 800 70 6 pesos para que lo disfrutes hasta el dia 2 de noviembre b 2025 revisa tu celular en pocos minutos te enviaremos el detalle de tu saldo";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_09 */ @Then("^Validar la transcripción Menu Principal, Asterisco, Comprar Paquetes$")
    public void validarTranscripcionMenuPrincipalAsteriscoComprarPaquetes() {
        String textoEsperado = "ingreso whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 quieres consultar el saldo de tu linea prepago marca 1 quieres comprar paquetes marca 2 quieres recargar tu linea prepago marca 3 quieres consultar tus productos financiados marca 4 quieres revisar tus paquetes activos marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 hola ahora puedes recargar y comprar paquetes en nuestros canales digitales con claro davi plata neki pc o tarjeta de credito y lo mejor recibe 3 por 1 en datos y minutos de tus paquetes marca 1 para paquete de 7500 pesos por 6 dias con llamadas ilimitadas 14 gb de navegacion y redes sociales marca 2 para paquete de 8500 pesos por 7 dias con llamadas ilimitadas 2 gb de navegacion y redes sociales marca 3 para mas opciones de paquetes marca 4 para mas opciones de recarga";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_010 */ @Then("^Validar la transcripción Menu Principal, Asterisco, Comprar Paquetes, Mas opciones de paquetes$")
    public void validarTranscripcionMenuPrincipalAsteriscoComprarPaquetesMasOpcionesDePaquetes() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 de las siguientes opciones seleccione servicios relacionado con tu consulta linea prepago terminada en 9 4 7 marca 1 linea postpago terminada en 1 1 3 marca 2 linea postpago terminada en 9 7 4 marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 quieres consultar el saldo de tu linea prepago marca 1 quieres comprar paquetes marca 2 quieres recargar tu linea prepago marca 3 quieres consultar tus productos financiados marca 4 quieres revisar tus paquetes activos marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 hola ahora puedes recargar y comprar paquetes en nuestros canales digitales con claro david plata neki tc o tarjeta de credito y lo mejor recibe 3 por 1 en datos y minutos de tus paquetes marca 1 para paquete de 7500 pesos por 6 dias con llamadas ilimitadas 14 gb de navegacion y redes sociales marca 2 para paquete de 8500 pesos por 7 dias con llamadas ilimitadas 2 gigas de navegacion y redes sociales marca 3 para mas opciones de paquetes marca 4 para mas opciones de recarga marca 1 para paquete de 4500 pesos por 3 dias con llamadas ilimitadas 400 mb de navegacion y redes sociales marca 2 para que de 12000 pes por 10 dias con llamadas ilimitadas 35 gb de navegacion y redes sociales marca 3 para paquete de 22000 pesos por 20 dias con llamadas ilimitadas 75 gb de navegacion y redes sociales marca 4 para mas opciones de paquetes marca 0 para regresar al menu anterior";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_011 */ @Then("^Validar la transcripción Menu Principal, Asterisco, Comprar Paquetes, Mas Opciones De Recarga$")
    public void validarTranscripcionMenuPrincipalAsteriscoComprarPaquetesMasOpcionesDeRecarga() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 quieres consultar el saldo de tu linea prepago marca 1 quieres comprar paquetes marca 2 quieres recargar tu linea prepago marca 3 quieres consultar tus productos financiados marca 4 quieres revisar tus paquetes activos marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 hola ahora puedes recargar y comprar paquetes en nuestros canales digitales con claro david plata neki tc o tarjeta de credito y lo mejor recibe 3 por 1 en datos y minutos de tus paquetes marca 1 para paquete de 7500 pesos por 6 dias con llamadas ilimitadas 14 gb de navegacion y redes sociales marca 2 para paquete de 8500 pesos por 7 dias con llamadas ilimitadas 2 gigas de navegacion y redes sociales marca 3 para mas opciones de paquetes marca 4 para mas opciones de recarga marca 1 para recarga de 30000 pesos marca 2 para recarga de $20000 marca 3 para recarga de 10000 pesos marca 4 para mas opciones de recarga marca 0 para regresar al menu anterior";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_012 */ @Then("^Validar la transcripción Menu Principal, Asterisco, Recargar Linea Prepago$")
    public void validarTranscripcionMenuPrincipalAsteriscoRecargarLineaPrepago() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago y este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wifi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 quieres consultar el saldo de tu linea prepago marca 1 quieres comprar paquetes marca 2 quieres recargar tu linea prepago marca 3 quieres consultar tus productos financiados marca 4 quieres revisar tus paquetes activos marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 hola numero 724 te invitamos a marcar asterisco 260 para comprar paquetes recargas y mucho mas gracias por ser parte de la familia claro";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_013 */ @Then("^$")
    public void validarTranscripcion() {
        String textoEsperado = "";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_014 */ @Then("^Validar la transcripción Menu Principal, Asterisco, Paquetes Activos$")
    public void validarTranscripcionMenuPrincipalAsteriscoPaquetesActivos() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claros marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por consulta paquetes activos y este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para informacion general o activar tu servicio marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 quieres consultar el saldo de tu linea prepago marca 1 quieres comprar paquetes marca 2 quieres recargar tu linea prepago marca 3 quieres consultar tus productos financiados marca 4 quieres revisar tus paquetes activos marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 actualmente no tienes paquetes activos marca 1 si deseas activar un paquete marca 2 si deseas regresar al menu principal hola ahora puedes recargar y comprar paquetes con david plata meki pf y tarjeta de credito para recargar con pin marca 1 para comprar paquetes y recargas marca 2 o 3 para finalizar tu llamada por favor ingresa el numero de pin";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_015 */ @Then("^Validar la transcripción Menu Principal, Asterisco, Paquetes Activos, Retorno Menu Principal$")
    public void validarTranscripcionMenuPrincipalAsteriscoPaquetesActivosRetornoMenuPrincipal() {
        String textoEsperado = "";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_016 */ @Then("^Validar la transcripción Menu Principal, Numeral, Soporte De Voz$")
    public void validarTranscripcionMenuPrincipalNumeralSoporteDeVoz() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal la opción que visitaste tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si necesitas soporte de voz o datos para tu linea móvil claro marca 1 te pasaste a claro con tu mismo numero y no has recibido tu sim card marca 2 te robaron tu celular o lo perdiste marca 3 necesitas reconectar tu linea por perdida o robo marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 18 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_017 */ @Then("^Validar la transcripción Menu Principal, Numeral, Te Pasaste a Claro$")
    public void validarTranscripcionMenuPrincipalNumeralTePasasteaClaro() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 quieres corregirlo marca 2 hemos notado que llamaste recientemente por consulta paquetes activos y este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si necesitas soporte de voz o datos para tu linea movil claro marca 1 te pasaste claro con tu mismo numero y no has recibido tu sim card marca 2 te robaron tu celular o lo perdiste marca 3 necesitas reconectar tu linea por perdida o robo marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 marca los 10 digitos del numero de celular que quieres pasar a claro el numero ingresado es 3 1 2 5 4 5 7 9 4 7 si es correcto marca 1 de lo contrario marca 2 tenemos una informacion importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu peticion queja o reclamo pqr sera contestada a mas tardar en 25 b septiembre 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entendera resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamacion siempre que presentes la pqr antes de la fecha de pago oportuno";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_018 */ @Then("^Validar la transcripción Menu Principal, Numeral, Robo De Celular$")
    public void validarTranscripcionMenuPrincipalNumeralRoboDeCelular() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 quieres corregirlo marca 2 hemos notado que llamaste recientemente por consulta paquetes activos si este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wifi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si necesitas soporte de voz o datos para tu linea movil claro marca 1 te pasaste a claro con tu mismo numero y no has recibido tu sim card marca 2 te robaron tu celular o lo perdiste marca 3 necesitas reconectar tu linea por perdida o robo marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 tu seguridad es muy importante para nosotros te comunicaremos con un asesor que te ayudara con tu solicitud tenemos una informacion importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu peticion queja o reclamo pqr sera contestada a mas tardar en 25 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entendera resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamacion siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 311 2000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_019 */ @Then("^Validar la transcripción Menu Principal, Numeral, Reconectar Linea$")
    public void validarTranscripcionMenuPrincipalNumeralReconectarLinea() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 quieres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal no tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wifi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si necesitas soporte de voz o datos para tu linea móvil claro marca 1 te pasaste a claro con tu mismo numero y no has recibido tu sim card marca 2 te robaron tu celular o lo perdiste marca 3 necesitas reconectar tu linea por perdida o robo marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 la opción que visitaste no es valida si necesitas soporte de voz o datos para tu linea móvil claro marca 1 te pasaste a claro con tu mismo numero y no has recibido tu sim card marca 2 te robaron tu celular o lo perdiste";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_020 */ @Then("^Validar la transcripción Menu Principal, Op1, Info General$")
    public void validarTranscripcionMenuPrincipalOp1InfoGeneral() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_021 */ @Then("^Validar la transcripción Menu Principal, Op1, Activar Roaming Internacional$")
    public void validarTranscripcionMenuPrincipalOp1ActivarRoamingInternacional() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 con el servicio de roaming internacional podrás hacer y recibir llamadas navegar en internet y usar otros servicios de datos desde tu móvil claro en diferentes países del mundo donde claro tiene convenios sin necesidad de cambiar tu numero móvil marca 1 si deseas recibir un mensaje donde podrás administrar y conocer todo nuestro portafolio de ofertas de servicio de roaming internacional marca 2 para comunicarte con un asesor 3 si deseas hacer mas consultas en nuestro menú principal o cuelga para finalizar tu llamada a continuación enviaremos un mensaje de texto donde podrás activar el servicio de roaming definir el tiempo de uso y también podrás adquirir paquetes de acuerdo a tu lugar de destino gracias por contactarnos hasta pronto";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_022 */ @Then("^Validar la transcripción Menu Principal, Op1, Activar Roaming Internacional, Op2$")
    public void validarTranscripcionMenuPrincipalOp1ActivarRoamingInternacionalOp2() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal la opción tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 con el servicio de roaming internacional podrás hacer y recibir llamadas navegar en internet y dejar otros servicios de datos desde tu móvil claro en diferentes países del mundo donde claro tiene convenios sin necesidad de cambiar tu numero móvil marca 1 si deseas recibir un mensaje donde podrás administrar y conocer todo nuestro portafolio de ofertas de servicio de roaming internacional marca 2 para comunicarte con un asesor 3 si deseas hacer mas consultas en nuestro menú principal o cuelga para finalizar tu llamada tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 18 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_023 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Equipos$")
    public void validarTranscripcionMenuPrincipalOp1AdquirirEquipos() {
        String textoEsperado = "claro ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wifi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fijo hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 con el servicio de roaming internacional podrás hacer y recibir llamadas navegar en internet y usar otros servicios de datos desde tu móvil claro en diferentes países del mundo donde claro tiene convenio sin necesidad de cambiar tu numero móvil marca 1 si deseas recibir un mensaje donde podrás administrar y conocer todo nuestro portafolio de ofertas de servicio de roaming internacional marca 2 para comunicarte con un asesor 3 si deseas hacer mas consultas en nuestro menú principal o cuelga para finalizar tu llamada tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 18 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_024 */ @Then("^Validar la transcripción Menu Principal, Op1, Pasarte a Claro y Adquirir Servicios Claro, Servicios Moviles y Servicios Hogar$")
    public void ValidarlatranscripcionMenuPrincipalOp1PasarteaClaroyAdquirirServiciosClaroServiciosMovilesyServiciosHogar() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 en este momento nos encontramos atendiendo un evento atípico en nuestra red que ocasiona variaciones en la prestación del servicio de voz nuestro equipo técnico se encuentra trabajando para mejorar tu experiencia hemos notado que llamaste recientemente por tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios de hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 18 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_025 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Servicios Claro, Pasarte Claro Con Tu Mismo Numero$")
    public void ValidarlatranscripcionMenuPrincipalOp1AdquirirServiciosClaroPasarteClaroConTuMismoNumero() {
        String textoEsperado = "ingreso whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming si este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 digita el numero celular que quieres pasar a claro el numero digitado es 3 1 2 5 4 5 7 9 4 7 tu consulta será atendida por medio de whatsapp";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_026 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Servicios Claro, Claro Video$")
    public void ValidarlatranscripcionMenuPrincipalOp1AdquirirServiciosClaroClaroVideo() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 quieres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fijo hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 claro video te recomienda descarga la aplicación claro video regístrate y empieza a disfrutar del mejor contenido de series y peliculas en tus géneros favoritos drama acción documentales y mucho mas por tan solo 1300 pesos para volver al menú anterior marca 1 o 2 para finalizar la llamada muchas gracias por contactarte con nosotros hasta pronto";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_027 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Servicios Claro, Claro Musica$")
    public void ValidarlatranscripcionMenuPrincipalOp1AdquirirServiciosClaroClaroMusica() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claros marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fijo hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 en pocos minutos te enviaremos un mensaje de texto para que comiences a disfrutar de claro musica sin consumir tus datos para volver al menú anterior marca 1 o 2 para finalizar la llamada muchas gracias por contactarte con nosotros hasta pronto";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_028 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Servicios Claro, Adquirir Servicio Asistencia Claro, Activar Servicio$")
    public void ValidarlatranscripcionMenuPrincipalOp1AdquirirServiciosClaroAdquirirServicioAsistenciaClaroActivarServicio() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claros marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 quieres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 marca 1 para realizar la activación del servicio marca 2 para mayor información otra es para solicitud de asistencia marca 9 para volver al menú anterior tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 18 de septiembre de 2025 por el mismo numero que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_029 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Servicios Claro, Adquiri Servicio Asistencia Claro, Mayor Informacion$")
    public void ValidarlatranscripcionMenuPrincipalOp1AdquirirServiciosClaroAdquirirServicioAsistenciaClaroMayorInformacion() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 marca 1 para realizar la activación del servicio marca 2 para mayor información otras para solicitud de asistencia marca 9 para volver al menú anterior tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 19 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 311 2000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_030 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Servicios Claro, Adquirir Servicio Asistencia Claro, Solicitud de Asistencia$")
    public void ValidarlatranscripcionMenuPrincipalOp1AdquirirServiciosClaroAdquirirServicioAsistenciaClaroSolicituddeAsistencia() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 la opción que dije marca 1 para realizar la activación del servicio marca 2 para mayor información otra es para solicitud de asistencia marca 9 para volver al menú anterior tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 19 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_031 */ @Then("^Validar la transcripción Menu Principal, Op1, Adquirir Servicios Claro, Larga Distancia Internacional$")
    public void ValidarlatranscripcionMenuPrincipalOp1AdquirirServiciosClaroLargaDistanciaInternacional() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wifi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 para información general marca 1 quieres activar el servicio de roaming internacional marca 2 si quieres adquirir de contado o a cuotas equipos celulares accesorios y tecnología para tu hogar marca 3 para pasarte a claro con tu mismo numero comprar canales adicionales o adquirir claro musica y claro video marca 4 quieres consultar registrar o modificar tus elegidos móvil de tu linea fija hogar marca 5 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 quieres comprar servicios móviles servicios hogar u otros servicios como win sports mas y hbo marca 1 para pasarte a claro con tu mismo numero marca 2 conoce y disfruta claro video marca 3 conoce y disfruta claro musica marca 4 quieres conocer y adquirir el servicio de asistencia claro marca 5 para larga distancia internacional marca 6 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 tu consulta será atendida por medio de whatsapp";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_032 */ @Then("^Validar la transcripción Menu Principal, Op1, Elegidos Movil Familia$")
    public void ValidarTranscripcionValidarlatranscripcionMenuPrincipalOp1ElegidosMovilFamilia() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal la opción que digitaste tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wifi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si necesitas soporte de voz o datos para tu linea móvil claro marca 1 te pasaste claro con tu mismo numero y no has recibido tu sim card marca 2 te robaron tu celular o lo perdiste marca 3 necesitas reconectar tu linea por perdida o robo marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 19 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago bienvenido a claro te saludamos del área preferencial de soporte técnico tengo el gusto de atenderte con quien me estoy comunicando";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_033 */ @Then("^Validar la transcripción Menu Principal, Op2, Perdida De Celular$")
    public void ValidarlatranscripcionMenuPrincipalOp2PerdidaDeCelular() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos que visitas traslados o tu clave wifi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 perdiste o robaron tu celular marca 1 necesitas realizar la reconexión de tu linea por perdida o robo marca 2 necesitas registrar tu equipo marca 3 quieres conocer información sobre reciclaje de equipos y baterías marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 tu seguridad es muy importante para nosotros te comunicaremos con un asesor que te ayudara con tu solicitud tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 19 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_034 */ @Then("^Validar la transcripción Menu Principal, Op2, Reconeccion$")
    public void ValidarlatranscripcionMenuPrincipalOp2Reconeccion() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tu servicio marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 perdiste o robaron tu celular marca 1 necesitas realizar la reconexión de tu linea por perdida o robo marca 2 necesitas registrar tu equipo marca 3 quieres conocer información sobre reciclaje de equipos y baterías marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 comunicaremos con una asesor que te ayudara con tu solicitud tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 19 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_035 */ @Then("^Validar la transcripción Menu Principal, Op2, Registrar Equipo$")
    public void ValidarlatranscripcionMenuPrincipalOp2RegistrarEquipo() {
        String textoEsperado = "claro ingresa a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming si este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 perdiste o robaron tu celular marca 1 necesitas realizar la reconexión de tu linea por perdida o robo marca 2 necesitas registrar tu equipo marca 3 quieres conocer información sobre reciclaje de equipos y baterías marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 genial tu equipo ya se encuentra registrado te enviaremos un mensaje de texto a tu celular con la información de registro del equipo si quieres registrar un equipo diferente al que estas utilizando en esta llamada debes insertar una sim en ese equipo y llamar al asterisco 611 gracias por comunicarte con nosotros hasta pronto";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_036 */ @Then("^Validar la transcripción Menu Principal, Op2, Reciclaje De Equipos$")
    public void ValidarlatranscripcionMenuPrincipalOp2ReciclajeDeEquipos() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por roaming y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 perdiste o robaron tu celular marca 1 necesitas realizar la reconexión de tu linea por perdida o robo marca 2 necesitas registrar tu equipo marca 3 quieres conocer información sobre reciclaje de equipos y baterías marca 4 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 como apoyo al mejoramiento ambiental mundial claro te invita a traer los equipos accesorios y baterías celulares que no se encuentran en uso a cualquiera de nuestros centros de atención y ventas y depositarlos en las canecas que tenemos disponibles en breves minutos enviaremos un mensaje a tu celular con el link a muy claro a donde podrás consultar el centro de atención y ventas mas cercano a donde te encuentras marca 1 si deseas repetir esta información marca 9 para volver al menú principal o 0 si quieres finalizar esta llamada";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_037 */ @Then("^Validar la transcripción Menu Principal, Op3, Desistir, Cancelar Servicios Hogar o Movil$")
    public void ValidarlatranscripcionMenuPrincipalOp3DesistirCancelarServiciosHogaroMovil() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si quieres desistir o consultar información relacionada con cancelación de tus servicios marca 1 para consultar el estado o radicar una petición queja reclamo o recurso de reposición marca 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 para cancelar tu servicio móvil marca 1 cancelar servicios adicionales marca 2 si quieres volver al menú principal marca 9 tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 19 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_038 */ @Then("^Validar la transcripción Menu Principal, Op3, Desistir, Cancelar Servicios Adicionales$")
    public void ValidarlatranscripcionMenuPrincipalOp3DesistirCancelarServiciosAdicionales() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 1 2 5 4 5 7 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tu servicio marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si quieres desistir o consultar información relacionada con cancelación de tus servicios marca 1 para consultar el estado o radicar una petición queja reclamo o recurso de reposición marca 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 para cancelar tus servicios hogar o móvil marca 1 cancelar servicios adicionales marca 2 si quieres volver al menú principal marca 9 tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 19 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_039 */ @Then("^Validar la transcripción Menu Principal, Op3, Radicar Peticiones, Consultar Peticiones Quejas o Recursos Desde Web$")
    public void ValidarlatranscripcionMenuPrincipalOp3RadicarPeticionesConsultarPeticionesQuejasoRecursosDesdeWeb() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 quieres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumo compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si quieres desistir o consultar información relacionada con cancelación de tus servicios marca 1 para consultar el estado o radicar una petición queja reclamo o recurso de reposición marca 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 si quieres consultar tus peticiones quejas o recursos desde nuestra pagina web marca 1 para escuchar el estado de tus peticiones quejas o recursos de los últimos 30 días marca 2 radicar peticiones quejas o recursos marca 3 para volver al menú principal marca 9 0 para finalizar la llamada revisa tu celular hemos enviado un mensaje con el link para que continúes la consulta de tus peticiones quejas o reclamos";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_040 */ @Then("^Validar la transcripción Menu Principal, Op3, Radicar Peticiones, Op2, Si es de la linea que llamas Op1$")
    public void ValidarlatranscripcionMenuPrincipalOp3RadicarPeticionesOp2SiEsDeLaLineaQueLlamaOp1() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si quieres desistir o consultar información relacionada con cancelación de tus servicios marca 1 para consultar el estado o radicar una petición queja reclamo o recurso de reposición marca 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 si quieres consultar tus peticiones quejas o recursos desde nuestra pagina web marca 1 para escuchar el estado de tus peticiones quejas o recursos de los últimos 30 días marca 2 radicar peticiones quejas o recursos marca 3 para volver al menú principal marca 9 0 para finalizar la llamada si es de la linea que llamas marca 1 si es un servicio diferente marca 2 para repetir esta información marca 0 tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 22 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_041 */ @Then("^Validar la transcripción Menu Principal, Op3, Radicar Peticiones, Op2, Si es de un servicio diferente Op2$")
    public void ValidarlatranscripcionMenuPrincipalOp3RadicarPeticionesOp2SiEsDeUnServicioDiferenteOp2() {
        String textoEsperado = "ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja repuso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si quieres desistir o consultar información relacionada con cancelación de tus servicios marca 1 para consultar el estado o radicar una petición queja reclamo o recurso de reposición marca 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 si quieres consultar tus peticiones quejas o recursos desde nuestra pagina web marca 1 para escuchar el estado de tus peticiones quejas o recursos de los últimos 30 días marca 2 radicar peticiones quejas o recursos marca 3 para volver al menú principal marca 9 0 para finalizar la llamada si es de la linea que llamas marca 1 si es un servicio diferente marca 2 para repetir esta información marca 0 por favor visita el numero de tu documento del identificación seguido de la tecla numeral";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_042 */ @Then("^Validar la transcripción Menu Principal, Op3, Radicar Peticiones, Radicar Peticiones Quejas o Recursos$")
    public void ValidarlatranscripcionMenuPrincipalOp3RadicarPeticionesRadicarPeticionesQuejasoRecursos() {
        String textoEsperado = "ingresa whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claros marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tu servicio marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 si quieres desistir o consultar información relacionada con cancelación de tus servicios marca 1 para consultar el estado o radicar una petición queja reclamo o recurso de reposición marca 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 si quieres consultar tus peticiones quejas o recursos desde nuestra pagina web marca 1 para escuchar el estado de tus peticiones quejas o recursos de los últimos 30 días marca 2 radicar peticiones quejas o recursos marca 3 para volver al menú principal marca 9 0 para finalizar la llamada tenemos una información importante para ti cuando desees marca 9 si necesitas comunicarte con un asesor tu petición queja o reclamo pqr será contestada a mas tardar en 22 de septiembre de 2025 por el mismo medio que la presentaste si tu pqr no es atendida en la fecha indicada se entenderá resuelta a tu favor si la pqr es por tu factura puedes presentarla dentro de los 6 meses siguientes al vencimiento del pago oportuno recuerda que no debes pagar las sumas en reclamación siempre que presentes la pqr antes de la fecha de pago oportuno te invitamos a continuar tus consultas por whatsapp al 3112000";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_043 */ @Then("^Validar la transcripción Menu Principal, Op4, Claro Pay$")
    public void ValidarlatranscripcionMenuPrincipalOp4ClaroPay() {
        String textoEsperado = "claro ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claros marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 quieres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago y este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 conoce mas de nuestra billetera digital claro marcando a 1 conoce mas de nuestra tarjeta de crédito claro MasterCard marcando 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 sabias que puedes tener un cupo preaprobado de hasta 100000 pesos solicítalo fácil ingresa en la app claro pay boton préstamo tu desbarate acepta términos y condiciones nueva claropay el poder de una billetera digital en tus manos paga tus facturas claro servicios públicos recarga tu linea móvil y mucho mas en un solo lugar tu consulta será atendida por medio de whatsapp";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_044 */ @Then("^Validar la transcripción Menu Principal, Op4, Claro Pay Master Card$")
    public void ValidarlatranscripcionMenuPrincipalOp4ClaroPayMasterCard() {
        String textoEsperado = "claro ingreso a whatsapp y ahorra tiempo podras consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menu principal marca 3 quieres consultar otro servicio marca 4 para repetir este menu marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por equipos financiados si este es el motivo de tu llamada marca 1 o 9 para ir al menu principal tienes dudas con tu factura pagos saldo consumo compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios movil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para informacion general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelacion de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 conoce mas de nuestra billetera digital claropay marcando 1 escuchar nuevamente estas opciones marca 9 si quieres volver al menu principal marca 0 sabias que puedes tener un cupo preaprobado de hasta 100000 pesos solicitalo facil ingresa en la app claro boton prestamo tu desbare acepta terminos y condiciones nueva claro el poder de una billetera digital en tus manos paga tus facturas claro servicios publicos recarga tu linea movil y mucho mas en un solo lugar tu consulta sera atendida por medio de whatsapp";
        validarTranscripcion(textoEsperado);
    }

    /* IVR_045 */ @Then("^Validar la transcripción Menu Principal, Op4, Claro Pay Master Card, Op2$")
    public void ValidarlatranscripcionMenuPrincipalOp4ClaroPayMasterCardOp2() {
        String textoEsperado = "claro ingreso a whatsapp y ahorra tiempo podrás consultar tu plan pagar tu factura y mucho mas quieres hacerlo marca 1 si quieres comprar alguno de nuestros servicios claro marca 2 para continuar con nuestro menú principal marca 3 quieres consultar otro servicio marca 4 para repetir este menú marca 9 por favor ingresa el numero de celular que vas a consultar tu numero de celular es 3 1 2 5 4 5 7 9 4 7 es correcto marca 1 eres corregirlo marca 2 hemos notado que llamaste recientemente por saldo prepago si este es el motivo de tu llamada marca 1 o 9 para ir al menú principal tienes dudas con tu factura pagos saldo consumos compra de paquetes y otros detalles marca asterisco si necesitas soporte de tus servicios móvil o fijos gestionar visitas traslados o tu clave wi-fi marca numeral para información general o activar tus servicios marca 1 para gestionar tus equipos marca 2 si necesitas radicar una queja recurso o solicitar la cancelación de tus servicios marca 3 si quieres conocer servicios especiales para ti marca 4 escuchar nuevamente estas opciones marca 9 conoce mas de nuestra billetera digital claropay marcando a 1 conoce mas de nuestra tarjeta de crédito claropay MasterCard marcando 2 escuchar nuevamente estas opciones marca 9 si quieres volver al menú principal marca 0 sabias que puedes tener un cubo preaprobado de hasta 100000 pesos solicítalo fácil ingresa en la app claropay boton préstamo tu desvay acepta términos y condiciones nuevo claropay el poder de una billetera digital en tus manos paga tus facturas claro servicios públicos recarga tu linea móvil y mucho mas en un solo lugar si ya tienes la tarjeta de crédito claro pay marca 1 si aun no la tienes y quieres conocer sus beneficios marca 2 si quieres volver al menú principal marca 0 compra tecnología con los siguientes beneficios 20% de devolución en tu primera compra 10% a partir de tu segunda compra claro 10% de devolución autorizando el pago automático de tu factura claro además acumula un punto Colombia por cada 1500 pesos en tus compras diferidas a 2 o mas cuotas pulsando tu tarjeta de crédito en comercios diferentes a claro para solicitar la marca 1 si quieres volver al menú principal marca 0 a continuación recibirás un SMS con la información gracias por comunicarte con nosotros";
        validarTranscripcion(textoEsperado);
    }

    // Método central de validación
    private void validarTranscripcion(String textoEsperado) {
        try {
            String esperadoNormalizado = normalizar(textoEsperado);
            String transcripcionNormalizada = normalizar(transcription);

            double porcentaje = calcularPorcentajeCoincidencia(transcripcionNormalizada, esperadoNormalizado);

            assertTrue(
                    porcentaje >= UMBRAL_COINCIDENCIA,
                    () -> "La transcripción no coincide lo suficiente.\n" +
                            "Esperado: " + esperadoNormalizado + "\n" +
                            "Transcripción: " + transcripcionNormalizada + "\n" +
                            "Coincidencia: " + porcentaje + "%"
            );

            System.out.println("✅ Coincidencia aceptable (" + porcentaje + "%)");
            System.out.println("✅ Texto Esperado");
            System.out.println(esperadoNormalizado);

            // 🔹 Guardar en EstadoPrueba para el reporte final
            EstadoPrueba.transcripcion = transcription;
            EstadoPrueba.textoEsperado = textoEsperado;

        } finally {
            EliminarAudioEnCelular.ejecutar(udid, RUTA_ARCHIVO_CELULAR);
        }
    }

    private String normalizar(String texto) {
        if (texto == null) return "";
        texto = texto.toLowerCase()
                // Números en palabra -> dígitos
                .replaceAll("\\bcero\\b", "0")
                .replaceAll("\\buno\\b", "1").replaceAll("\\bdos\\b", "2")
                .replaceAll("\\btres\\b", "3").replaceAll("\\bcuatro\\b", "4")
                .replaceAll("\\bcinco\\b", "5").replaceAll("\\bseis\\b", "6")
                .replaceAll("\\bsiete\\b", "7").replaceAll("\\bocho\\b", "8")
                .replaceAll("\\bnueve\\b", "9").replaceAll("\\bdiez\\b", "10")
                .replaceAll("\\bonce\\b", "11").replaceAll("\\bdoce\\b", "12")
                // Números ya escritos (para asegurar)
                .replaceAll("\\b(1|2|3|4|5|6|7|8|9|10|11|12)\\b", "$1")
                // Quitar acentos
                .replaceAll("[áàäâ]", "a").replaceAll("[éèëê]", "e")
                .replaceAll("[íìïî]", "i").replaceAll("[óòöô]", "o")
                .replaceAll("[úùüû]", "u")
                // Quitar signos y espacios extra
                .replaceAll("[,.;:!?]", "").replaceAll("\\s+", " ").trim();
        return texto;
    }

    private double calcularPorcentajeCoincidencia(String t1, String t2) {
        LevenshteinDistance distancia = new LevenshteinDistance();
        int dist = distancia.apply(t1, t2);
        int maxLen = Math.max(t1.length(), t2.length());
        return Math.round((1 - ((double) dist / maxLen)) * 10000.0) / 100.0; // 2 decimales
    }
}
